---
# tasks file for setup_server

- name: Gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"


- name: Set grub options
  ansible.builtin.import_tasks: grub.yml

- name: Configure network interface
  ansible.builtin.import_tasks: network.yml

- name: Show CPU info
  ansible.builtin.import_tasks: cpu.yml
